services:
  db:
    container_name: erp_db
    image: postgres:17
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME}
  erp:
    container_name: erp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

#   redis:
#     container_name: erp_redis
#     image: redis:7-alpine

#   celery:
#     build: .
#     volumes:
#       - .:/app
#     command: celery -A django_celery_project worker -l info
#     env_file:
#       - .env
#     depends_on:
#       - redis
#       - db

#   celery-beat:
#     build: .
#     volumes:
#       - .:/app
#     command: ./start_celery_beat.sh
#     env_file:
#       - .env
#     depends_on:
#       - redis
#       - db


volumes:
  postgres_data:
